application: web2kindle
version: 1
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media
  
- url: /Send.*
  script: SendToKindle.py

- url: /.*
  static_files: index.html
  upload: index.html